#################################   ALIAS   #################################

alias battery-info='ioreg -c AppleSmartBattery | grep -i Capacity'
function show-colors-combi() { clear; for fore in `seq 30 37`; do printf "\e[${fore}m \\\e[${fore}m \e[m\n"; for mode in 1 4 5; do printf "\e[${fore};${mode}m \\\e[${fore};${mode}m \e[m"; for back in `seq 40 47`; do printf "\e[${fore};${back};${mode}m \\\e[${fore};${back};${mode}m \e[m"; done; echo; done; echo; done; printf " \\\e[m\n" }
alias show-255colors="seq 0 255 | xargs -I {} printf '\033[38;5;{}m{} '"
#alias ls='ls -G' # for MacOS
alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias l='clear && ls -la'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias gm='git mv'
alias gs='git status'
alias gss='git status -sb'
alias ga='git add'
alias gan='git add -n'
alias gaa='git add -A'
alias gb='git branch'
alias gba='git branch -a'
alias gbm='git branch -m'
alias gbd='git branch -d'
alias gbs='git switch'
alias gbb='git switch -'
alias gbc='git switch -c'
alias gcmsg='git commit -m'
alias gl='git log'
alias glo='git log --oneline'
alias gd='git diff'
alias gr='git remote'
alias grv='git remote -v'
alias grs='git remote show'
alias gra='git remote add'
alias grr='git remote remove'
alias gf='git fetch'
alias gpu='git push'
alias gpd='git pull'

alias python='python3'
alias pip='pip3'
