"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[git_branch]
symbol = ""
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmd_duration]
format = "[⏱ $duration]($style)"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"
